run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
    - e2e

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck